theforeman/foreman_kubevirt

app/models/foreman_kubevirt/kubevirt.rb
app/views/compute_resources_vms/form/kubevirt/_base.html.erb
app/views/images/form/_kubevirt.html.erb

In order to create a VM based on image, the user should create an image
under Compute Resource --> Create Image, and provide the name of the
image on the registry.
The image will be set as the registryDisk of the vm (should be renamed
to containerDisk in a following PR).
One property of 'registryDisk' is missing ('path') and should be added
in a following PR as well

Create VM based on image

---

app/models/foreman_kubevirt/kubevirt.rb

KubeVirt's VMs can be associated with Foreman's hosts by the 'mac'
property of the server (which represents the VM's mac address)

Support associate VM

---

foreman_kubevirt.gemspec

fog-kubevirt supports kubevirt api v1alpha3 which contains recent API
changes.

Use fog-kubevirt 0.20.0

---

app/models/foreman_kubevirt/kubevirt.rb
app/views/compute_resources_vms/form/kubevirt/_network.html.erb

The 'Boot VM from Network' shares the same behavior as the 'primary'
checkbox, therefore it could be removed and the functionality will be
based on the 'primary' network interface.

Replace Boot VM from Network checkbox with primary

---

app/controllers/foreman_kubevirt/concerns/api/compute_resources_controller_extensions.rb
app/views/api/v2/compute_resources/kubevirt.json.rabl
lib/foreman_kubevirt/engine.rb

Example of creating a compute resource: 
```
POST http://localhost:3000/api/compute_resources/30
{
"compute_resource" : {
"name" : "ssstam",
"provider" : "KubeVirt",
"hostname": "XXXX",
"token":   "..." ,
"namespace" : "default", 
"api_port" : 8443
}
}
```
Example of creating a host:
```
POST http://localhost:3000/api/hosts
{
"location_id" : 1,
"organization_id" : 2,
"host" : {
"name" : "dd",
"location_id" : 1,
"organization_id" : 2,
"environment_id" : 1,
"ip" : "192.168.124.31",
"hostgroup_id" : 1,
"compute_resource_id" : 30,
"provision_method":"build",
"compute_attributes" : {
"cores" : "1",
"volumes_attributes" : {"_delete":"", "id" :"", "name":"gluster-default-volume", "capacity":"1"}
},
"interfaces_attributes": {
"0" : {"domain_id" : "1", "name" : "chase-prevett", "subnet_id" : "1", …
```

Add Compute Resource API

---

getting-started.md

we can get around most of the things by using a proper `jsonpath`

use fewer shell commands to obtain the kube secret

---

app/assets/javascripts/compute_resources/kubevirt/volume.js
app/models/concerns/fog_extensions/kubevirt/volume.rb
app/models/foreman_kubevirt/kubevirt.rb
app/views/compute_resources_vms/form/kubevirt/_volume.html.erb
foreman_kubevirt.gemspec
lib/foreman_kubevirt/engine.rb

This PR depends on https://github.com/fog/fog-kubevirt/pull/82
The Storage dialog under the Virtual Machine tab of 'Create Host' was changed.
Its new look is:
This PR depends on fog-kubevirt's PR: https://github.com/fog/fog-kubevirt/pull/83

Support Storage Class when creating VM

---

app/models/foreman_kubevirt/kubevirt.rb

We should support deployments that use only POD networks.
Fixes https://github.com/masayag/foreman_kubevirt/issues/25

Allow pod network only

---

app/models/foreman_kubevirt/kubevirt.rb

* When provision image based host, the image disk should be the bootable device.
* There should be an option to add additional PVC to the image device.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1695645
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1695644

Fix create host from image

---

README.md
Rakefile

Tests should be executed from the foreman directory since they rely on
resources exist on that repository.
Therefore the default task of Rake shouldn't invoke the tests.

Do not run tests by default

---

app/models/concerns/fog_extensions/kubevirt/volume.rb
app/models/foreman_kubevirt/kubevirt.rb

In order to support compute profile, new_vm and new_volume should be
implemented properly.
This PR depends on fog/fog-kubevirt#118 which included in fog-kubevirt-1.2.4

Support compute profiles

---

app/models/foreman_kubevirt/kubevirt.rb
test/unit/foreman_kubevirt_test.rb

Fixes https://projects.theforeman.org/issues/26658

Raise error in case of booting from volume and from image

---

app/assets/javascripts/foreman_kubevirt/kubevirt.js

Running the following command:
`rake 'plugin:assets:precompile[foreman_kubevirt]' RAILS_ENV=production`
fails with:
```
Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax,
harmony mode must be enabled with Uglifier.new(:harmony => true).
```
Removing the constant didn't change much on the code itself.

Clear assets precompile error

---

test/models/compute_resources/kubevirt_test.rb

Added the following two tests:
1. Verify client raises StandardError exception
2. Verify client raises FingerprintException exception

Fixes #26732 - Add compute resource tests

---

app/models/foreman_kubevirt/kubevirt.rb
app/views/compute_resources_vms/index/_kubevirt.html.erb
app/views/compute_resources_vms/show/_kubevirt.html.erb
test/unit/foreman_kubevirt_test.rb

The PR fixes few memory issues:
* The memory default value should be a string (same as passed in
arguments)
* Memory default value should be provided as string (this is the
expected format in the VM arguments)
* Tests should be updated no to provide memory or CPU in order to rely
on the defaults
* Memory should be shown in a normalized way in the UI
* When creating VM, the memory should be converted to MB, while before
this PR it was considered to be MiB which lead to a lower amount of
memory than expected.

Fixes #26656 - Fix memory issues

---

app/models/foreman_kubevirt/kubevirt.rb
test/unit/foreman_kubevirt_test.rb

Creating a host without additional volumes doesn't pass any value for
volumes_attributes, therefore we should assume it may be nil.

Fix #26784 - Create VM with image only should pass

---

app/models/foreman_kubevirt/kubevirt.rb
foreman_kubevirt.gemspec
lib/foreman_kubevirt/engine.rb

By upgrading to fog-kubevirt-1.3.0, the memory for the created vm can be
specified with its units, so we'll get the exact desired memory.

Use fog-kubevirt 1.3.0

---

CHANGELOG.md
lib/foreman_kubevirt/version.rb

* Support User Data (#103)
* Fix #26784: Create VM with image only should pass (#102)
* Fixes #26656 - Fix memory issues (#100)
* Add compute resource tests (#99)
* Add tests for default values (#98)
* Add message expectation to tests (#97)

Bump to 0.1.3

---

app/models/foreman_kubevirt/kubevirt.rb
app/views/compute_resources/form/_kubevirt.html.erb

There were several issues with the token: 
1. The validation should run in test connection and when submitting the form, and they didn't
2. test connection button  didn't work properly, the token got disabled after "Test connection" because the JS function searched for compute_resource_password but in the erb file we sent the id as compute_resource_token

Fixes #27494 - Fix validation and test_connection

---

app/models/foreman_kubevirt/kubevirt.rb

- Removing a volume should be in any case that vm/volumes/interface creation fails
- If cni_provider or network are missing (for example in the cli) we should raise an error

Add some fixes

---

test/factories/host_factories.rb

The environment was extracted to foreman_puppet and isn't relevant for the test.

Remove environment from the host factory

---

CHANGELOG.md
lib/foreman_kubevirt/version.rb

I'm debating releasing this for Foreman 3.12. The alternative is to patch the dependency in packaging and move forward with https://github.com/theforeman/foreman_kubevirt/pull/160.

Release 0.2.0
